- name: check chezmoi is already installed
  stat:
    path: /usr/local/bin/chezmoi
  register: chezmoi_installed
  tags:
    - dotfiles 
    - chezmoi

- name: download chezmoi binary
  shell: sh -c "$(curl -fsLS git.io/chezmoi)"
  tags:
    - dotfiles
    - chezmoi


- name: download and unzip 1password-cli 
  unarchive:
    src: "https://cache.agilebits.com/dist/1P/op/pkg/{{ one_password_version }}/op_linux_amd64_{{ one_password_version }}.zip"
    dest: /usr/local/bin
    include: op
    remote_src: yes
  become: true
  when: not op_installed.stat.exists
  tags:
    - dotfiles 


