- name: check chezmoi is already installed
  stat:
    path: /usr/local/bin/chezmoi
  register: chezmoi_installed
  tags:
    - dotfiles 
    - chezmoi

- name: download chezmoi binary
  shell: sh -c "$(curl -fsLS git.io/chezmoi)"
  when: not chezmoi_installed.stat.exists
  tags:
    - dotfiles
    - chezmoi

- name: move chezmoi to path
  copy:
    src: bin/chezmoi
    dest: /usr/local/bin/chezmoi
  become: true
  when: not chezmoi_installed.stat.exists
  tags:
    - dotfiles
    - chezmoi

- name: sync dotfiles from repo
  command: "chezmoi init --apply {{ github_username }}" 
  environment:
    OP_SESSION_my: "{{ op_login.stdout | regex_search('\"(.+)\"', '\\1') | first }}"
  tags:
    - dotfiles
    - chezmoi
