- name: check 1password CLI is already installed
  stat:
    path: /usr/local/bin/op 
  register: op_installed
  tags:
    - dotfiles 

- name: download and unzip 1password-cli 
  unarchive:
    src: "https://cache.agilebits.com/dist/1P/op/pkg/{{ one_password_version }}/op_linux_amd64_{{ one_password_version }}.zip"
    dest: /usr/local/bin
    include: op
    remote_src: yes
  become: true
  when: not op_installed.stat.exists
  tags:
    - dotfiles 

- name: login to 1password-cli
  expect:
    command: op signin my.1password.com 1@gmail.com code 
    responses:
      Enter(.*): "pass"
  no_log: false 
  register: op_login
  tags:
    - dotfiles

- name: debug
  debug:
    msg: "{{ op_login.stdout | regex_search('\"(.+)\"', '\\1') | first }}"
  tags:
    - dotfiles
