- name: install blueman
  apt:
    name:
      - bluez
      - blueman
    state: present
  notify:
    - restart pulse as user
  tags:
    - bluetooth

- name: auto-switch between HSP/HSF and A2DP
  lineinfile:
    dest: /etc/pulse/default.pa
    regex: "^load-module module-bluetooth-policy"
    state: present
    line: "load-module module-bluetooth-policy auto_switch=2"
  notify:
    - restart pulse as user
  tags:
    - bluetooth      

- name: do not auto power on the bluetooth device
  command: gsettings set org.blueman.plugins.powermanager auto-power-on false
  become: yes
  become_user: "{{ user.name }}"
  tags:
    - bluetooth

- name: unblock the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: no
    state: stopped
  when: bluetooth.disable == False
  tags:
    - bluetooth

- name: enable and start the bluetooth service
  service:
    name: bluetooth.service
    enabled: yes
    state: started
  when: bluetooth.disable == False
  tags:
    - bluetooth

- name: disable and stop the bluetooth service
  service:
    name: bluetooth.service
    enabled: no
    state: stopped
  when: bluetooth.disable == True
  tags:
    - bluetooth

- name: block the bluetooth service
  service:
    name: "rfkill-block@bluetooth.service"
    enabled: yes
    state: started
  when: bluetooth.disable == True
  tags:
    - bluetooth

