- name: (Ubuntu) Install blueman
  become: true
  apt:
    name:
      - bluez
      - blueman
    state: present
  notify:
    - restart pulse as user
  when: ansible_distribution == "Ubuntu"
  tags:
    - bluetooth

- name: (Fedora) Install blueman
  become: true
  dnf:
    name:
      - bluez
      - blueman
      - python3-cairo
      - python3-gobject
    state: present
  when: ansible_distribution == "Fedora"
  tags:
    - bluetooth

- name: Check bluez-monitor conifiguration is already copied
  stat:
    path: /etc/pipewire/media-session.d/bluez-monitor.conf
  register: bluez_monitor_config_copied
  tags:
    - bluetooth 

- name: Copy bluez-monitor config
  become: true
  copy:
    src: bluez-monitor.conf
    dest: /etc/pipewire/media-session.d/bluez-monitor.conf 
    mode: u=rw,g=r,o=r
  when: 
    - ansible_distribution == "Fedora"
    - bluez_monitor_config_copied.stat.exists
  tags:
    - bluetooth

- name: Do not auto power on the bluetooth device
  command: gsettings set org.blueman.plugins.powermanager auto-power-on false
  become: false 
  tags:
    - bluetooth

- name: Unblock the bluetooth service
  become: true
  service:
    name: "bluetooth.service"
    enabled: no
    state: stopped
  when: bluetooth.disable == false
  tags:
    - bluetooth

- name: Enable and start the bluetooth service
  become: true
  service:
    name: bluetooth.service
    enabled: yes
    state: started
  when: bluetooth.disable == false
  tags:
    - bluetooth

- name: Disable and stop the bluetooth service
  become: true
  service:
    name: bluetooth.service
    enabled: no
    state: stopped
  when: bluetooth.disable == true
  tags:
    - bluetooth

- name: Block the bluetooth service
  become: true
  service:
    name: "bluetooth.service"
    enabled: yes
    state: started
  when: bluetooth.disable == true
  tags:
    - bluetooth

