- name: (Ubuntu) Add apt-key for Spotify
  become: true
  apt_key:
    url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
    state: present
  when: ansible_distribution == "Ubuntu"
  tags:
    - gui
    - spotify

- name: (Ubuntu) Add Spotify repo list
  become: true
  apt_repository:
    filename: spotify.list
    repo: deb http://repository.spotify.com stable non-free
    state: present
  when: ansible_distribution == "Ubuntu"
  tags:
    - gui
    - spotify

- name: (Ubuntu) Install Spotify
  become: true
  apt:
    name: spotify-client
    state: present
  when: ansible_distribution == "Ubuntu"
  tags:
    - gui
    - spotify
