- name: (Fedora) Add flatpak Spotify repo
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  when: ansible_distribution == "Fedora"
  tags:
    - gui
    - spotify

- name: (Fedora) Install Spotify
  flatpak:
    name: com.spotify.Client
    state: present
    method: user
  when: ansible_distribution == "Fedora"
  tags:
    - gui
    - spotify

- name: (Ubuntu) Add apt-key for spotify
  become: true
  apt_key:
    url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
    state: present
  when: ansible_distribution == "Ubuntu"
  tags:
    - gui
    - spotify

- name: (Ubuntu) Add spotify repo list
  become: true
  apt_repository:
    filename: spotify.list
    repo: deb http://repository.spotify.com stable non-free
    state: present
  when: ansible_distribution == "Ubuntu"
  tags:
    - gui
    - spotify

- name: (Ubuntu) Install spotify
  become: true
  apt:
    name: spotify-client
    state: present
  when: ansible_distribution == "Ubuntu"
  tags:
    - gui
    - spotify
