- name: Check Telegram is already installed
  stat:
    path: /home/{{ ansible_user_id }}/Apps/Telegram/Telegram
  register: telegram_installed
  tags:
    - gui
    - telegram 

- name: Download and unzip Telegram 
  unarchive:
    src: https://telegram.org/dl/desktop/linux
    dest: /home/{{ ansible_user_id }}/Apps
    remote_src: yes
  when: not telegram_installed.stat.exists
  tags:
    - gui
    - telegram 

- name: Create desktop entry and binary for Telegram
  shell: "(/home/{{ ansible_user_id }}/Apps/Telegram/Telegram >/dev/null 2>&1 &)"
  tags:
    - gui
    - toolbox
