- name: Check Toolbox is already installed
  stat:
    path: /home/{{ ansible_user_id }}/Apps/Toolbox/jetbrains-toolbox
  register: toolbox_installed
  tags:
    - gui
    - toolbox

- name: Create directory for Toolbox
  file:
    path: /home/{{ ansible_user_id }}/Apps/Toolbox
    state: directory
  tags:
    - gui
    - toolbox

- name: Get latest release URL of Toolbox app
  uri:
    url: https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release
    return_content: true
  register: release
  when: not toolbox_installed.stat.exists
  tags:
    - gui
    - toolbox

- name: Download and unzip Toolbox
  unarchive:
    src: "{{ release.json.TBA[0].downloads.linux.link }}"
    dest: /home/{{ ansible_user_id }}/Apps/Toolbox
    remote_src: yes
    extra_opts:
      - --strip-components=1
  when: not toolbox_installed.stat.exists
  tags:
    - gui
    - toolbox

- name: Create desktop entry and binary for Toolbox
  shell: "(/home/{{ ansible_user_id }}/Apps/Toolbox/jetbrains-toolbox >/dev/null 2>&1 &)"
  tags:
    - gui
    - toolbox
