- name: Install LightDM
  become: true
  dnf:
    name:
      - xorg-x11-drv-amdgpu
      - xorg-x11-drv-ati
      - xorg-x11-drv-evdev
      - xorg-x11-drv-fbdev
      - xorg-x11-drv-intel
      - xorg-x11-drv-libinput
      - xorg-x11-drv-nouveau
      - xorg-x11-drv-openchrome
      - xorg-x11-drv-qxl
      - xorg-x11-drv-vesa
      - xorg-x11-drv-vmware
      - xorg-x11-drv-wacom
      - xorg-x11-drv-wacom-serial-support
      - xorg-x11-fonts-misc
      - xorg-x11-server-Xorg
      - xorg-x11-server-common
      - xorg-x11-xauth
      - xorg-x11-xinit
    state: present
  when: ansible_distribution == "Fedora"
  tags:
    - display
    - display-manager
    - lightdm

- name: Install LightDM
  become: true
  apt:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present
  when: ansible_distribution == "Ubuntu"
  tags:
    - display
    - display-manager
    - lightdm

- name: Enable LightDM
  become: true
  service:
    name: lightdm.service
    enabled: yes
  tags:
    - display
    - display-manager
    - lightdm

- name: Create background dir
  become: true
  file:
    path: /usr/share/backgrounds
    state: directory
  tags:
    - display
    - display-manager
    - lightdm

- name: Add LightDM greeter background image
  become: true
  copy:
    src: bg.png
    dest: /usr/share/backgrounds/bg.png
  tags:
    - display
    - display-manager
    - lightdm

- name: Set LightDM greeter background
  become: true
  lineinfile:
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    regexp: "^background="
    state: present
    line: "background=/usr/share/backgrounds/bg.png"
  tags:
    - display
    - display-manager
    - lightdm

- name: Hide user images
  become: true
  lineinfile:
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    regexp: "^hide-user-image="
    state: present
    line: "hide-user-image=true"
  tags:
    - display
    - display-manager
    - lightdm

- name: Set LightDM greeter theme
  become: true
  lineinfile:
    dest: /usr/share/xgreeters/lightdm-gtk-greeter.desktop
    regexp: "^Exec="
    state: present
    line: "Exec=lightdm-gtk-greeter"
  tags:
    - display
    - display-manager
    - lightdm

- name: Set dpi for LightDM
  become: true
  lineinfile:
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
    regexp: "^xft-dpi="
    state: present
    line: "xft-dpi={{ display.lightdm.target_dpi }}"
  tags:
    - display
    - display-manager
    - lightdm
