- name: Install dnf-plugins-core
  become: true
  dnf:
    name:
      - dnf-plugins-core
    state: present
  when:
    - ansible_distribution == "Fedora"
    - display.driver == "nvidia"
  tags:
    - display
    - nvidia

- name: Enable Copr repo t0xic0der/nvidia-auto-installer-for-fedora
  become: true
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: t0xic0der/nvidia-auto-installer-for-fedora
  when:
    - ansible_distribution == "Fedora"
    - display.driver == "nvidia"
  tags:
    - display
    - nvidia

- name: Install autoinstaller for NVIDIA drivers
  become: true
  dnf:
    name:
      - nvautoinstall
    state: present
  when:
    - ansible_distribution == "Fedora"
    - display.driver == "nvidia"
  tags:
    - display
    - nvidia

# TODO
#- name: Install NVIDIA drivers
#  become: true
#  shell: | 
#    nvautoinstall --rpmadd
#    nvautoinstall --driver
#  when:
#    - ansible_distribution == "Fedora"
#    - display.driver == "nvidia"
#  tags:
#    - display
#    - nvidia
