- name: Add custom xsession
  become: true
  copy:
    dest: /usr/share/xsessions/i3.desktop
    mode: u=rw,g=r,o=r 
    content: |
      [Desktop Entry]
      Name=i3
      Exec=/etc/X11/xinit/xinitrc
  tags:
    - display 
    - xinit 

- name: Add custom xinitrc 
  become: true
  copy:
    src: xinitrc
    dest: /etc/X11/xinit/xinitrc
    mode: u=rwx,g=rx,o=rx
  tags:
    - display
    - xinit

