- name: install musl-dev (required dependency)
  apt:
   name: musl-dev
   state: present
  tags:
    - i3

- name: get latest release URL of autodisplay from github  
  uri:
    url: https://api.github.com/repos/lpicanco/i3-autodisplay/releases/latest
    return_content: true
  register: release
  tags:
    - i3

- name: download latest release of autodisplay 
  get_url:
    url: "{{ release.json.assets[0].browser_download_url }}"
    dest: /usr/local/bin/autodisplay
  tags:
    - i3

- name: make autodisplay file executable 
  file:
    path: /usr/local/bin/autodisplay
    state: file 
    mode: a+x
  tags:
    - i3
  
