- name: "[Ubuntu] Install musl-dev (required dependency)"
  become: true
  apt:
    name: musl-dev
    state: present
  when: ansible_distribution == "Ubuntu"
  tags:
    - i3

- name: "[Fedora] Install musl-dev (required dependency)"
  become: true
  dnf:
    name: musl-devel
    state: present
  when: ansible_distribution == "Fedora"
  tags:
    - i3

- name: Get latest release URL of autodisplay from github  
  uri:
    url: https://api.github.com/repos/lpicanco/i3-autodisplay/releases/latest
    return_content: true
  register: release
  tags:
    - i3

- name: Download latest release of autodisplay
  become: true
  get_url:
    url: "{{ release.json.assets[0].browser_download_url }}"
    dest: /usr/local/bin/autodisplay
  tags:
    - i3

- name: Make autodisplay file executable
  become: true
  file:
    path: /usr/local/bin/autodisplay
    state: file 
    mode: a+x
  tags:
    - i3
