- name: "[Ubuntu] Install ui tools for i3"
  become: true
  apt:
    name:
    - rofi 
    - dunst
    - polybar
    state: present
  when: ansible_distribution == "Ubuntu"
  tags:
    - i3 

- name: "[Fedora] Install ui tools for i3"
  become: true
  dnf:
    name:
    - rofi
    - dunst
    - polybar
    state: present
  when: ansible_distribution == "Fedora"
  tags:
    - i3 
