- name: Check kitty is already installed
  stat:
    path: /home/{{ ansible_user_id }}/.local/kitty.app
  register: kitty_installed
  tags:
    - terminal
    - kitty

- name: Fetch kitty installer code
  uri:
    url: https://sw.kovidgoyal.net/kitty/installer.sh
    return_content: true
  register: kitty_source_code
  when: not kitty_installed.stat.exists
  tags:
    - terminal
    - kitty

- name: Install kitty
  shell: "{{ kitty_source_code.content }}"
  when: not kitty_installed.stat.exists
  tags:
    - terminal
    - kitty

- name: Link kitty
  become: true
  file:
    src: /home/{{ ansible_user_id }}/.local/kitty.app/bin/kitty
    dest: /usr/local/bin/kitty
    state: link
  when: not kitty_installed.stat.exists
  tags:
    - terminal
    - kitty

- name: Copy kitty desktop to .local/share/applications
  copy:
    mode: +x
    src: /home/{{ ansible_user_id }}/.local/kitty.app/share/applications/kitty.desktop
    dest: /home/{{ ansible_user_id }}/.local/share/applications/kitty.desktop
  when: not kitty_installed.stat.exists
  tags:
    - terminal
    - kitty

- name: Update kitty icon link in desktop file
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.local/share/applications/kitty.desktop
    regexp: "^Icon="
    state: present
    line: "Icon=/home/{{ ansible_user_id }}/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png"
  when: not kitty_installed.stat.exists
  tags:
    - terminal
    - kitty
      
# see next
- name: Remove rxvt-unicode (because of fuck you)
  become: true
  dnf:
    name: rxvt-unicode
    state: absent
  tags:
    - terminal
    - kitty

# see https://superuser.com/questions/1270462/how-to-make-firefox-open-cli-app-in-specified-terminal/1469035#1469035
- name: https://www.amazon.com/s?k=crutch
  become: true
  file:
    src: /home/{{ ansible_user_id }}/.local/kitty.app/bin/kitty
    dest: /usr/local/bin/rxvt
    state: link
  tags:
    - terminal
    - kitty

