- name: install everyday utils
  apt:
    name:
      - git
      - curl
      - wget
      - htop
      - jq
      - zsh
      - apache2-utils # mostly for ab
      - ranger
      - sshpass
    state: present
  become: true
  tags:
    - terminal 

- import_tasks: oh-my-zsh.yaml
- import_tasks: neovim.yaml

