- name: check zsh is already setup
  stat:
    path: /home/{{ ansible_user_id }}/.zshrc
  register: zsh_installed
  tags:
    - terminal

- name: cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  when: not zsh_installed
  tags:
    - terminal

- name: creating new ~/.zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  when: not zsh_installed
  tags:
    - terminal

- name: set default shell for user
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
  tags:
    - terminal

# https://askubuntu.com/questions/910821/programs-installed-via-snap-not-showing-up-in-launcher
- name: (Ubuntu) export all directories (for snap)
  become: yes
  lineinfile:
    path: /etc/zsh/zprofile
    regexp: "^emulate*"
    line: "emulate sh -c 'source /etc/profile'"
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal

- name: set theme for zsh
  lineinfile:
    path: ~/.zshrc
    regexp: "^ZSH_THEME*"
    line: 'ZSH_THEME="avit"'
  when: not zsh_installed
  tags:
    - terminal
