- name: cloning oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  become: false
  tags:
    - terminal

- name: creating new ~/.zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
  become: false
  tags:
    - terminal

- name: set default shell for user
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags:
    - terminal

# https://askubuntu.com/questions/910821/programs-installed-via-snap-not-showing-up-in-launcher
- name: export all directories (for snap)
  become: yes
  lineinfile:
    path: /etc/zsh/zprofile
    regexp: "^emulate*"
    line: "emulate sh -c 'source /etc/profile'"
  tags:
    - terminal 

- name: set theme for zsh
  lineinfile:
    path: ~/.zshrc
    regexp: "^ZSH_THEME*"
    line: 'ZSH_THEME="avit"'
  become: false
  tags:
    - terminal

