- name: Check zsh is already installed
  stat:
    path: /home/{{ ansible_user_id }}/.zshrc
  register: zsh_installed
  tags:
    - terminal
    - oh_my_zsh

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: /home/{{ ansible_user_id }}/.oh-my-zsh
  when: not zsh_installed.stat.exists
  tags:
    - terminal
    - oh_my_zsh

- name: Set default shell for user
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags:
    - terminal
    - oh_my_zsh

# https://askubuntu.com/questions/910821/programs-installed-via-snap-not-showing-up-in-launcher
- name: (Ubuntu) export all directories (for snap)
  become: yes
  lineinfile:
    path: /etc/zsh/zprofile
    regexp: "^emulate*"
    line: "emulate sh -c 'source /etc/profile'"
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal
    - oh_my_zsh

- name: Install powerlevel10k theme 
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/{{ ansible_user_id }}/.oh-my-zsh/themes/powerlevel10k
    depth: 1
  tags:
    - terminal
    - oh_my_zsh

- name: Install zsh-autosuggestion plugin 
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ ansible_user_id }}/.oh-my-zsh/plugins/zsh-autosuggestions
    depth: 1
  tags:
    - terminal
    - oh_my_zsh

- name: Install zsh-syntax-highlighting plugin
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git 
    dest: /home/{{ ansible_user_id }}/.oh-my-zsh/plugins/zsh-syntax-highlighting
    depth: 1
  tags:
    - terminal
    - oh_my_zsh

