- name: Check zsh is already installed
  stat:
    path: /home/{{ ansible_user_id }}/.zshrc
  register: zsh_installed
  tags:
    - terminal

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: /home/{{ ansible_user_id }}/.oh-my-zsh
  when: not zsh_installed.stat.exists
  tags:
    - terminal

- name: Create new ~/.zshrc
  copy:
    src: /home/{{ ansible_user_id }}/.oh-my-zsh/templates/zshrc.zsh-template
    dest: /home/{{ ansible_user_id }}/.zshrc
  when: not zsh_installed.stat.exists
  tags:
    - terminal

- name: Set default shell for user
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  tags:
    - terminal

# https://askubuntu.com/questions/910821/programs-installed-via-snap-not-showing-up-in-launcher
- name: (Ubuntu) export all directories (for snap)
  become: yes
  lineinfile:
    path: /etc/zsh/zprofile
    regexp: "^emulate*"
    line: "emulate sh -c 'source /etc/profile'"
  when: ansible_distribution == "Ubuntu"
  tags:
    - terminal

- name: Set theme for zsh
  lineinfile:
    path: /home/{{ ansible_user_id }}/.zshrc
    regexp: "^ZSH_THEME*"
    line: 'ZSH_THEME="avit"'
  when: not zsh_installed.stat.exists
  tags:
    - terminal
