- name: Create .local/share/applications
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - /home/{{ ansible_user_id }}/.local/share/applications
    - /home/{{ ansible_user_id }}/.local/bin
  tags:
    - shared_deps
