- name: (Fedora) Install shared dependencies
  become: true
  dnf:
    name:
      - flatpak
      - dbus-daemon
      - dbus-x11
    state: present
  when:
    - ansible_distribution == "Fedora"
  tags:
    - shared_deps