- name: (Fedora) Install shared dependencies
  become: true
  dnf:
    name:
      - flatpak
      - dbus-daemon
      - dbus-x11
      - openssl
      - nss
      - mesa-dri-drivers
      - glx-utils
      - libglvnd
    state: present
  when:
    - ansible_distribution == "Fedora"
  tags:
    - shared_deps