- name: (Fedora) Install shared dependencies
  become: true
  dnf:
    name:
      - flatpak
      - fuse
      - dbus-daemon
      - dbus-x11
      - openssl
      - nss
      - mesa-dri-drivers
      - glx-utils
      - libglvnd
      - xrandr
      - wmname
      - setxkbmap
      - kbdd
      - gnome-font-viewer
      - openvpn
      - dnf-plugin-system-upgrade
      - fontawesome-free-fonts
      - material-icons-fonts
      - emoji-picker
      - python3-pip
      - tar
      - unzip
      - sqlite
      - ripgrep
      - ffmpeg
   state: present
  when:
    - ansible_distribution == "Fedora"
  tags:
    - shared_deps

- name: Install pexpect
  pip:
    name: pexpect
  when:
    - ansible_distribution == "Fedora"
  tags:
    - shared_deps

