- name: (Fedora) Import RPM Fusion keys
  become: true
  rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
  when:
    - ansible_distribution == "Fedora"
  tags:
    - shared_deps

- name: (Fedora) Enable the RPM Fusion repository
  become: true
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when:
    - ansible_distribution == "Fedora"
  tags:
    - shared_deps

- name: Enable copr repos 
  become: true
  community.general.copr:
    host: "{{ item.host }}"
    state: enabled
    name: "{{ item.name }}" 
  when:
    - ansible_distribution == "Fedora"
  with_items:
    - host: copr.fedorainfracloud.org
      name: atim/i3status-rust 
    - host: copr.fedorainfracloud.org
      name: vishalvvr/fontawesome-fonts
  tags:
    - shared_deps 

- name: Add google chorome repo 
  become: true
  yum_repository:
    name: google-chrome
    description: google repo
    gpgcheck: yes
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64 
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
  when:
    - ansible_distribution == "Fedora"
  tags:
    - shared_deps 

